# -*- coding: utf-8 -*-
"""OCracle1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NqC5pjaVT-XC7T0NjvL9hVCIQF4cIFIM
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('mario.png')
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img_rgb)
plt.axis('off')
plt.title("Input Mario Image")
plt.show()

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
plt.imshow(gray, cmap='gray')
plt.axis('off')
plt.title("Grayscale Image")
plt.show()

avg_kernel = np.ones((3, 3), dtype=np.float32) / 9.0

smoothed = cv2.filter2D(gray, -1, avg_kernel)
plt.imshow(smoothed, cmap='gray')
plt.axis('off')
plt.title("Smoothed Image (After Averaging Filter)")
plt.show()

sobel_x = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
], dtype=np.float32)

sobel_y = np.array([
    [-1, -2, -1],
    [ 0,  0,  0],
    [ 1,  2,  1]
], dtype=np.float32)

grad_x = cv2.filter2D(smoothed, -1, sobel_x)
grad_y = cv2.filter2D(smoothed, -1, sobel_y)

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(grad_x, cmap='gray')
plt.title("Gradient in X direction")
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(grad_y, cmap='gray')
plt.title("Gradient in Y direction")
plt.axis('off')

plt.show()

grad_x_f = grad_x.astype(np.float32)
grad_y_f = grad_y.astype(np.float32)

edge_magnitude = np.sqrt(grad_x_f**2 + grad_y_f**2)

edge_magnitude = (edge_magnitude / edge_magnitude.max()) * 255
edge_magnitude = edge_magnitude.astype(np.uint8)

plt.imshow(edge_magnitude, cmap='gray')
plt.axis('off')
plt.title("Edge Magnitude Image")
plt.show()

threshold = 50
binary_edges = np.zeros_like(edge_magnitude)
binary_edges[edge_magnitude >= threshold] = 255
plt.imshow(binary_edges, cmap='gray')
plt.axis('off')
plt.title("Final Binary Edge Map")
plt.show()

gaussian_kernel = np.array([
    [1,  4,  7,  4,  1],
    [4, 16, 26, 16,  4],
    [7, 26, 41, 26,  7],
    [4, 16, 26, 16,  4],
    [1,  4,  7,  4,  1]
], dtype=np.float32)

gaussian_kernel /= gaussian_kernel.sum()
smoothed_gaussian = cv2.filter2D(gray, -1, gaussian_kernel)

plt.imshow(smoothed_gaussian, cmap='gray')
plt.axis('off')
plt.title("Gaussian Smoothed Image")
plt.show()

grad_x_g = cv2.filter2D(smoothed_gaussian, -1, sobel_x)
grad_y_g = cv2.filter2D(smoothed_gaussian, -1, sobel_y)

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(grad_x_g, cmap='gray')
plt.title("Gradient X (Gaussian Smoothed)")
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(grad_y_g, cmap='gray')
plt.title("Gradient Y (Gaussian Smoothed)")
plt.axis('off')

plt.show()

grad_x_f = grad_x_g.astype(np.float32)
grad_y_f = grad_y_g.astype(np.float32)

edge_magnitude_g = np.sqrt(grad_x_f**2 + grad_y_f**2)

edge_magnitude_g = (edge_magnitude_g / edge_magnitude_g.max()) * 255
edge_magnitude_g = edge_magnitude_g.astype(np.uint8)

plt.imshow(edge_magnitude_g, cmap='gray')
plt.axis('off')
plt.title("Edge Magnitude (Gaussian Smoothed)")
plt.show()

high_thresh = 80
low_thresh = 30

strong = 255
weak = 75

edges_dt = np.zeros_like(edge_magnitude_g)

edges_dt[edge_magnitude_g >= high_thresh] = strong


weak_mask = (edge_magnitude_g >= low_thresh) & (edge_magnitude_g < high_thresh)
edges_dt[weak_mask] = weak

final_edges = edges_dt.copy()

rows, cols = edges_dt.shape

for i in range(1, rows-1):
    for j in range(1, cols-1):
        if edges_dt[i, j] == weak:
            if np.any(edges_dt[i-1:i+2, j-1:j+2] == strong):
                final_edges[i, j] = strong
            else:
                final_edges[i, j] = 0

plt.imshow(final_edges, cmap='gray')
plt.axis('off')
plt.title("Final Binary Edge Map (Double Threshold)")
plt.show()

binary_final = np.zeros_like(final_edges)
binary_final[final_edges == 255] = 255

plt.imshow(binary_final, cmap='gray')
plt.axis('off')
plt.title("Final Binary Edge Map (Cleaned)")
plt.show()