# -*- coding: utf-8 -*-
"""OCRacle_assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ESAx3-meTYoLtNSFIw5fU5xR9sIEcVOg
"""

import numpy as np
import matplotlib.pyplot as plt
import cv2
img_bgr=cv2.imread("/content/Screenshot 2025-12-13 175936.png")
img_rgb = cv2.cvtColor(img_bgr,cv2.COLOR_BGR2RGB)
img_gray = cv2.cvtColor(img_bgr,cv2.COLOR_BGR2GRAY)
plt.figure(figsize=(6,6))
plt.imshow(img_rgb)
plt.title("original image")
plt.axis("off")
plt.show()

plt.figure(figsize=(6,6))
plt.imshow(img_gray,cmap="gray")
plt.title("Grayscale image")
plt.axis("off")
plt.show()

ker=np.array([[1,2,1],[2,4,2],[1,2,1]])*(1/16) #gaussion blur
img_ker = cv2.filter2D(img_gray,cv2.CV_64F,ker)
plt.figure(figsize=(6,6))
plt.imshow(img_ker,cmap="gray")
plt.title("somthened(blurred) image")
plt.axis("off")
plt.show()

ker_y = np.array([[-1,0,1],[-2,0,2],[-1,0,1]])
ker_x = np.array([[-1,-2,-1],[0,0,0],[1,2,1]])
img_kerx = cv2.filter2D(img_gray,cv2.CV_64F,ker_x)
img_kery= cv2.filter2D(img_gray,cv2.CV_64F,ker_y)
img_edge=(img_kerx)*(img_kerx) + (img_kery)*(img_kery)
img_edge=np.sqrt(img_edge)
img_edge=(img_edge/(np.max(img_edge)))*255
rows,cols=img_edge.shape
for i in range(rows):
  for j in range(cols):
    if img_edge[i,j] >=60:
      img_edge[i,j]=255
    else:
      img_edge[i,j]=0
plt.figure(figsize=(6,6))
plt.imshow(img_edge,cmap="gray")
plt.title("edge detected image")
plt.axis("off")
plt.show()