# -*- coding: utf-8 -*-
"""Nikhil_Beniwal_240693.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hWFVcbSrWq2k2IZOHFFvLAtrSARkciw-
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

img_path = "/content/Screenshot 2025-12-13 175936.png"
img_bgr = cv2.imread(img_path)

img_rgb = cv2.cvtColor(img_bgr,cv2.COLOR_BGR2RGB)
img_gray = cv2.cvtColor(img_bgr,cv2.COLOR_BGR2GRAY)
plt.figure(figsize=(8,8))
plt.imshow(img_rgb)
plt.title("Original Image")
plt.show()

plt.figure(figsize=(8,8))
plt.imshow(img_gray,cmap="gray")
plt.title("Grayscale Image")
plt.show()

ker = (1/16) * np.array([[1,2,1],[2,4,2],[1,2,1]])
img_sm = cv2.filter2D(img_gray,cv2.CV_64F,ker)
plt.figure(figsize=(8,8))
plt.imshow(img_sm,cmap="gray")
plt.title("Smoothened(Blurred) image")

plt.show()

sob_x=np.array([[-1,0,1],[-2,0,2],[-1,0,1]])
sob_y=np.array([[-1,-2,-1],[0,0,0],[1,2,1]])
img_sobelx=cv2.filter2D(img_gray,cv2.CV_64F,sob_x)
img_sobely=cv2.filter2D(img_gray,cv2.CV_64F,sob_y)
img_edge=np.sqrt((img_sobelx)*(img_sobelx)+(img_sobely)*(img_sobely))
c=np.max(img_edge)
img_edge=(img_edge/c)*255
rows,columns=img_edge.shape
for i in range(rows):
  for j in range(columns):
    if img_edge[i,j]>=85:
      img_edge[i,j]=255
    else:
      img_edge[i,j]=0
plt.figure(figsize=(8,8))

plt.imshow(img_edge,cmap="gray")
plt.title("Edge Detected")
plt.show()